// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForInsertResourceTags implements pgx.CopyFromSource.
type iteratorForInsertResourceTags struct {
	rows                 []InsertResourceTagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertResourceTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertResourceTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ResourceID,
		r.rows[0].Tag,
	}, nil
}

func (r iteratorForInsertResourceTags) Err() error {
	return nil
}

func (q *Queries) InsertResourceTags(ctx context.Context, arg []InsertResourceTagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"resource_tags"}, []string{"resource_id", "tag"}, &iteratorForInsertResourceTags{rows: arg})
}
