// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Module struct {
	Urn       string
	Name      string
	Project   string
	Configs   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Resource struct {
	ID              int64
	Urn             string
	Kind            string
	Name            string
	Project         string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	SpecConfigs     []byte
	StateStatus     string
	StateOutput     []byte
	StateModuleData []byte
	StateNextSync   pgtype.Timestamptz
	StateSyncResult []byte
	CreatedBy       string
	UpdatedBy       string
}

type ResourceDependency struct {
	ResourceID    int64
	DependencyKey string
	DependsOn     int64
}

type ResourceTag struct {
	Tag        string
	ResourceID int64
}

type Revision struct {
	ID          int64
	Reason      string
	CreatedAt   pgtype.Timestamptz
	ResourceID  int64
	SpecConfigs []byte
	CreatedBy   string
}

type RevisionTag struct {
	Tag        string
	RevisionID int64
}
